
server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.boot: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true