
server:
  port: 9000

logging:
  level:
    root: WARN
    org.springframework.boot: WARN
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    org.hibernate: ERROR
    hu.bme.compsec.sudoku: TRACE
  file:
    name: ./audit/auth-server.log